title: "my first blog post"
author: Eman-Ehab
email: myemail@domain.com

description: > # this means to ignore newlines until "baseurl:"
          consider it is a description
# social links

github_username: Eman-Ehab

show_excerpts: true # set to false to remove excerpts on the homepage


